server:
  port: 8026
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mhmt?useUnicode=true&amp&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: root

logging:
  level:
    root: info
    com:
      safety:
        school: debug

pagehelper:
  reasonable: false